name: test1
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        image:
          - "ubuntu:20.04"
          - "ubuntu:18.04"
          - "debian:10"
          - "debian:8"
          - "centos:8"
          - "centos:7"
    container:
      image: ${{ matrix.image }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./configure --with-localpetsc --enable-autodependencies
          make
